using Schema.Core.Data;
using Schema.Core.Schemes;

namespace Schema.Core.Schemes
{
    /// <summary>
    /// This class was auto-generated by Schema based on the 'Localization' data scheme.
    /// Do not modify this file directly. Changes may be overwritten.
    /// </summary>
    public partial class LocalizationScheme : SchemeWrapper<LocalizationEntry>
    {
  public enum Id		{
			INTRO_QUEST_TITLE,
			QUEST_1_DESCRIPTION,
			QUEST_TEST,
			Fancy_Brooch_Description,
			NPC_NAME_1,
		}
		

        public LocalizationScheme(DataScheme dataScheme) : base(dataScheme)
        {
        }

        protected override LocalizationEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry)
        {
            return new LocalizationEntry(dataScheme, dataEntry);
        }

    }

    public partial class LocalizationEntry : EntryWrapper
    {
        public LocalizationEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry)
        {
        }

        public string LocID => DataEntry.GetDataAsString("LocID");
        public string EnUS => DataEntry.GetDataAsString("en-US");
        /// <summary>
        /// Details about where this localized string appears to help the Localization team.
        /// </summary>
        public string Context => DataEntry.GetDataAsString("Context");
        public bool ReadyForTranslations => DataEntry.GetDataAsBool("ReadyForTranslations");
        public string EsES => DataEntry.GetDataAsString("es-ES");
        public string FrFR => DataEntry.GetDataAsString("fr-FR");
        public string DeDE => DataEntry.GetDataAsString("de-DE");
        public string ItIT => DataEntry.GetDataAsString("it-IT");
        public string JaJP => DataEntry.GetDataAsString("ja-JP");
        public string ZhCN => DataEntry.GetDataAsString("zh-CN");
        public string KoKR => DataEntry.GetDataAsString("ko-KR");
        public string RuRU => DataEntry.GetDataAsString("ru-RU");
        public string PtBR => DataEntry.GetDataAsString("pt-BR");
    }
}
