using Schema.Core.Data;
using Schema.Core.Schemes;

namespace Schema.Core.Schemes
{
    /// <summary>
    /// This class was auto-generated by Schema based on the 'Manifest' data scheme.
    /// Do not modify this file directly. Changes may be overwritten.
    /// </summary>
    public partial class ManifestScheme : SchemeWrapper<ManifestEntry>
    {

        public ManifestScheme(DataScheme dataScheme) : base(dataScheme)
        {
        }

        protected override ManifestEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry)
        {
            return new ManifestEntry(dataScheme, dataEntry);
        }

    }

    public partial class ManifestEntry : EntryWrapper
    {
        public ManifestEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry)
        {
        }

        public string SchemeName
        {
            get => _dataEntry.GetDataAsString("SchemeName");
            set => _dataScheme.SetDataOnEntry(_dataEntry, "SchemeName", value);
        }
        public string FilePath
        {
            get => _dataEntry.GetDataAsString("FilePath");
            set => _dataScheme.SetDataOnEntry(_dataEntry, "FilePath", value);
        }
        public string PublishTarget
        {
            get => _dataEntry.GetDataAsString("PublishTarget");
            set => _dataScheme.SetDataOnEntry(_dataEntry, "PublishTarget", value);
        }
    }
}
