using Schema.Core.Data;
using Schema.Core.Schemes;

namespace Schema.Core.Schemes
{
    /// <summary>
    /// This class was auto-generated by Schema based on the 'TODOs' data scheme.
    /// Do not modify this file directly. Changes may be overwritten.
    /// </summary>
    public partial class TODOsScheme : SchemeWrapper<TODOsEntry>
    {
        public TODOsScheme(DataScheme dataScheme) : base(dataScheme)
        {
        }

        protected override TODOsEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry)
        {
            return new TODOsEntry(dataScheme, dataEntry);
        }
    }

    public partial class TODOsEntry : EntryWrapper
    {
        public TODOsEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry)
        {
        }

        public string Title => _dataEntry.GetDataAsString("Title");
        public string Description => _dataEntry.GetDataAsString("Description");
        public string Status => _dataEntry.GetDataAsString("Status");
        public string TargetVersion => _dataEntry.GetDataAsString("TargetVersion");
        public bool AddedTooltips => _dataEntry.GetDataAsBool("Added Tooltips?");
        public string ItemType => _dataEntry.GetDataAsString("Item Type");
        public string ProjectArea => _dataEntry.GetDataAsString("Project Area");
    }
}
