using Schema.Core;
using Schema.Core.Data;
using Schema.Core.Schemes;
using UnityEngine;
using static Schema.Core.Schema;


    /// <summary>
    /// This class was auto-generated by Schema based on the 'Chests' data scheme.
    /// Do not modify this file directly. Changes may be overwritten.
    /// </summary>
    public partial class ChestsScheme : SchemeWrapper<ChestsEntry>
    {
        public const string SCHEMA_NAME = "Chests";
        
     
        public static class Ids
        {
         
            public const string BIG_CHEST = "BIG_CHEST";
     
        }

     
        public static SchemaResult<ChestsScheme> Get()
        {
            if (GetScheme(SCHEMA_NAME).Try(out var scheme, out var error))
            {
                return SchemaResult<ChestsScheme>.Pass(new ChestsScheme(scheme));
            }
            
            return error.CastError<ChestsScheme>();
        }
        
        public static SchemaResult<ChestsEntry> GetEntry(object entryId)
        {
            if (!Get().Try(out var scheme, out var schemeError))
            {
                return schemeError.CastError<ChestsEntry>();
            }
            
            return scheme.GetEntryById(entryId);
        }

        public ChestsScheme(DataScheme dataScheme) : base(dataScheme) {}

        protected override ChestsEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry) {
            return new ChestsEntry(dataScheme, dataEntry);
        }
    }

    [SerializeField]
    public partial class ChestsEntry : EntryWrapper
    {
        public ChestsEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry) {}

     
        public string ID => DataEntry.GetDataAsString("ID");
     
        public string RewardType1 => DataEntry.GetDataAsString("RewardType1");
     
        public int Amount1 => DataEntry.GetDataAsInt("Amount1");
     
        public string RewardType2 => DataEntry.GetDataAsString("RewardType2");
     
        public string Amount2 => DataEntry.GetDataAsString("Amount2");
 
    }

