// <auto-generated>
// This file was generated by Schema based on the 'Entities' data scheme.
// Any changes made directly to this file may be overwritten.
// </auto-generated>

using Schema.Core;
using Schema.Core.Data;
using Schema.Core.Schemes;
using static Schema.Core.Schema;

namespace ExampleProject.Schemes 
{

    /// <summary>
    /// Auto-generated strongly-typed wrapper for the 'Entities' data scheme.
    /// </summary>
    public partial class EntitiesScheme : SchemeWrapper<EntitiesEntry>
    {
        /// <summary>
        /// The canonical name of the data scheme.
        /// </summary>
        public const string SCHEMA_NAME = "Entities";
        
     
        /// <summary>
        /// Strongly-typed constants for identifier values in 'Entities'.
        /// </summary>
        public static class Ids
        {
         
            public const string PLAYER = "Player";
         
            public const string ENEMY = "Enemy";
     
        }

     
        public static SchemaResult<EntitiesScheme> Get()
        {
            if (GetScheme(SCHEMA_NAME).Try(out var scheme, out var error))
            {
                return SchemaResult<EntitiesScheme>.Pass(new EntitiesScheme(scheme));
            }
            
            return error.CastError<EntitiesScheme>();
        }
        
        public static SchemaResult<EntitiesEntry> GetEntry(object entryId)
        {
            if (!Get().Try(out var scheme, out var schemeError))
            {
                return schemeError.CastError<EntitiesEntry>();
            }
            
            return scheme.GetEntryById(entryId);
        }
        
        public EntitiesScheme(DataScheme dataScheme) : base(dataScheme) {}
        
        protected override EntitiesEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry) {
            return new EntitiesEntry(dataScheme, dataEntry);
        }
    }

    public partial class EntitiesEntry : EntryWrapper
    {
        /// <summary>
        /// Represents a single entry (row) in the 'Entities' data scheme.
        /// </summary>
        public EntitiesEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry) {}

     
        /// <summary>
        /// Gets the value of 'ID'.
        /// </summary>
     
        public string ID => DataEntry.GetDataAsString("ID");
     
        /// <summary>
        /// Move speed of the entity
        /// </summary>
     
        public float MoveSpeed => DataEntry.GetDataAsFloat("MoveSpeed");
 
    }
}
