using Schema.Core;
using Schema.Core.Data;
using Schema.Core.Schemes;
using UnityEngine;
using static Schema.Core.Schema;

namespace ExampleProject.Schemes 
{

    /// <summary>
    /// This class was auto-generated by Schema based on the 'Entities' data scheme.
    /// Do not modify this file directly. Changes may be overwritten.
    /// </summary>
    public partial class EntitiesScheme : SchemeWrapper<EntitiesEntry>
    {
        public const string SCHEMA_NAME = "Entities";
        
     
        public static class Ids
        {
         
            public const string PLAYER = "Player";
     
        }

     
        public static SchemaResult<EntitiesScheme> Get()
        {
            if (GetScheme(SCHEMA_NAME).Try(out var scheme, out var error))
            {
                return SchemaResult<EntitiesScheme>.Pass(new EntitiesScheme(scheme));
            }
            
            return error.CastError<EntitiesScheme>();
        }
        
        public static SchemaResult<EntitiesEntry> GetEntry(object entryId)
        {
            if (!Get().Try(out var scheme, out var schemeError))
            {
                return schemeError.CastError<EntitiesEntry>();
            }
            
            return scheme.GetEntryById(entryId);
        }

        public EntitiesScheme(DataScheme dataScheme) : base(dataScheme) {}

        protected override EntitiesEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry) {
            return new EntitiesEntry(dataScheme, dataEntry);
        }
    }

    [SerializeField]
    public partial class EntitiesEntry : EntryWrapper
    {
        public EntitiesEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry) {}

     
        public string ID => DataEntry.GetDataAsString("ID");
     
        /// <summary>
        /// Move speed of the entity
        /// </summary>
     
        public float MoveSpeed => DataEntry.GetDataAsFloat("MoveSpeed");
     
        public int Health => DataEntry.GetDataAsInt("Health");
     
        public string Name => DataEntry.GetDataAsString("Name");
 
    }
}
