// <auto-generated>
// This file was generated by Schema based on the 'Quests' data scheme.
// Any changes made directly to this file may be overwritten.
// </auto-generated>

using Schema.Core;
using Schema.Core.CodeGen;
using Schema.Core.Data;
using Schema.Core.Schemes;
using Schema.Runtime;
using static Schema.Core.Schema;


    /// <summary>
    /// Auto-generated strongly-typed wrapper for the 'Quests' data scheme.
    /// </summary>
    public partial class QuestsScheme : SchemeWrapper<QuestsEntry>
    {
        /// <summary>
        /// The canonical name of the data scheme.
        /// </summary>
        public const string SCHEMA_NAME = "Quests";
        
     
        /// <summary>
        /// Strongly-typed constants for identifier values in 'Quests'.
        /// </summary>
        public static class Ids
        {
         
            public const string QUEST_1 = "QUEST_1";
         
            public const string QUEST_2 = "QUEST_2";
     
        }

     
        public static SchemaResult<QuestsScheme> Get()
        {
            if (GetScheme(SCHEMA_NAME).Try(out var scheme, out var error))
            {
                return SchemaResult<QuestsScheme>.Pass(new QuestsScheme(scheme));
            }
            
            return error.CastError<QuestsScheme>();
        }
        
        public static SchemaResult<QuestsEntry> GetEntry(object entryId)
        {
            if (!Get().Try(out var scheme, out var schemeError))
            {
                return schemeError.CastError<QuestsEntry>();
            }
            
            return scheme.GetEntryById(entryId);
        }
        
        public QuestsScheme(DataScheme dataScheme) : base(dataScheme) {}
        
        protected override QuestsEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry) {
            return new QuestsEntry(dataScheme, dataEntry);
        }
    }

    public partial class QuestsEntry : EntryWrapper
    {
        /// <summary>
        /// Represents a single entry (row) in the 'Quests' data scheme.
        /// </summary>
        public QuestsEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry) {}

     
        /// <summary>
        /// Gets the value of 'ID'.
        /// </summary>
     
        public System.String ID => DataEntry.GetDataAsString("ID");
 
    }

