using Schema.Core;
using Schema.Core.Data;
using Schema.Core.Schemes;
using UnityEngine;
using static Schema.Core.Schema;


    /// <summary>
    /// This class was auto-generated by Schema based on the 'RewardType' data scheme.
    /// Do not modify this file directly. Changes may be overwritten.
    /// </summary>
    public partial class RewardTypeScheme : SchemeWrapper<RewardTypeEntry>
    {
        public const string SCHEMA_NAME = "RewardType";
        
     
        public static class Ids
        {
         
            public const string SEASHELLS = "SEASHELLS";
         
            public const string SILVER = "SILVER";
         
            public const string GEMS = "GEMS";
     
        }

     
        public static SchemaResult<RewardTypeScheme> Get()
        {
            if (GetScheme(SCHEMA_NAME).Try(out var scheme, out var error))
            {
                return SchemaResult<RewardTypeScheme>.Pass(new RewardTypeScheme(scheme));
            }
            
            return error.CastError<RewardTypeScheme>();
        }
        
        public static SchemaResult<RewardTypeEntry> GetEntry(object entryId)
        {
            if (!Get().Try(out var scheme, out var schemeError))
            {
                return schemeError.CastError<RewardTypeEntry>();
            }
            
            return scheme.GetEntryById(entryId);
        }

        public RewardTypeScheme(DataScheme dataScheme) : base(dataScheme) {}

        protected override RewardTypeEntry EntryFactory(DataScheme dataScheme, DataEntry dataEntry) {
            return new RewardTypeEntry(dataScheme, dataEntry);
        }
    }

    [SerializeField]
    public partial class RewardTypeEntry : EntryWrapper
    {
        public RewardTypeEntry(DataScheme dataScheme, DataEntry entry) : base(dataScheme, entry) {}

     
        public string ID => DataEntry.GetDataAsString("ID");
 
    }

