name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # or the version your project uses

    - name: List all files and directories
      run: ls -R

    - name: Restore dependencies
      run: dotnet restore Schema/Schema.sln

    - name: Build
      run: dotnet build Schema/Schema.sln --no-restore --configuration Release

    - name: Test with code coverage
      run: |
        dotnet test Schema/Schema.sln --no-build --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory TestResults \
          --logger "trx;LogFileName=TestResults.trx"

    - name: Report test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: "TestResults/**/*.trx"
        reporter: dotnet-trx
        fail-on-error: false

    - name: Publish code coverage
      uses: codecov/codecov-action@v3
      with:
        files: 'TestResults/**/coverage.cobertura.xml'
        fail_ci_if_error: true
        verbose: true

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: TestResults/**/coverage.cobertura.xml
